CREATE TABLE [dbo].[GameGoalEvent]
(
    Id INT NOT NULL,
    GameId INT NOT NULL,
    TypeCode INT NOT NULL,
    SortOrder INT NOT NULL,
    SituationCode INT NOT NULL,
    PeriodNumber INT NOT NULL,
    PeriodType INT NOT NULL,
    EventTypeName VARCHAR(100) NOT NULL,
    HomeTeamDefendingSide INT NOT NULL,
    SecondsIntoPeriod INT NOT NULL,
    SecondsLeftInPeriod INT NOT NULL,
    XCoordinate INT,
    YCoordinate INT,
    [Zone] INT NOT NULL,
    ShotType INT NOT NULL,
    ScoringPlayerTeamId INT NOT NULL,
    AssistOnePlayerId INT,
    AssistTwoPlayerId INT,
    ScoringPlayerId INT NOT NULL,
    GoalieId INT,
    HighlightClipSharingUrl VARCHAR(255) NOT NULL,
    HighlightClipId INT NOT NULL,
    DiscreetClipId INT NOT NULL,
    PptReplayUrl VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GameGoalEvent PRIMARY KEY(GameId, Id),
    FOREIGN KEY (GameId) REFERENCES GameRaw(Id),
    FOREIGN KEY (ScoringPlayerTeamId) REFERENCES Team(Id),
    FOREIGN KEY (ScoringPlayerId) REFERENCES Player(Id),
    FOREIGN KEY (AssistOnePlayerId) REFERENCES Player(Id),
    FOREIGN KEY (AssistTwoPlayerId) REFERENCES Player(Id),
    FOREIGN KEY (GoalieId) REFERENCES Player(Id)
);