CREATE TABLE [dbo].[GamePenaltyEvent]
(
    Id INT NOT NULL,
    GameId INT NOT NULL,
    TypeCode INT NOT NULL,
    SortOrder INT NOT NULL,
    SituationCode INT NOT NULL,
    PeriodNumber INT NOT NULL,
    PeriodType INT NOT NULL,
    EventTypeName VARCHAR(100) NOT NULL,
    HomeTeamDefendingSide INT NOT NULL,
    SecondsIntoPeriod INT NOT NULL,
    SecondsLeftInPeriod INT NOT NULL,
    CommittedByPlayerTeamId INT NOT NULL,
    DrawnByPlayerId INT,
    CommittedByPlayerId INT,
    ServedByPlayerId INT,
    XCoordinate INT,
    YCoordinate INT,
    [Zone] INT NOT NULL,
    Duration INT NOT NULL,
    PenaltyType INT NOT NULL,
    PenaltySeverity INT NOT NULL,
    CONSTRAINT PK_GamePenaltyEvent PRIMARY KEY(GameId, Id),
    FOREIGN KEY (GameId) REFERENCES GameRaw(Id),
    FOREIGN KEY (CommittedByPlayerTeamId) REFERENCES Team(Id),
    FOREIGN KEY (DrawnByPlayerId) REFERENCES Player(Id),
    FOREIGN KEY (CommittedByPlayerId) REFERENCES Player(Id),
    FOREIGN KEY (ServedByPlayerId) REFERENCES Player(Id)
);