CREATE TABLE [dbo].[GameGoalEvent]
(
    id INT NOT NULL,
    gameId INT NOT NULL,
    typeCode INT NOT NULL,
    sortOrder INT NOT NULL,
    situationCode INT NOT NULL,
    periodNumber INT NOT NULL,
    periodType INT NOT NULL,
    eventTypeName VARCHAR(100) NOT NULL,
    homeTeamDefendingSide INT NOT NULL,
    secondsIntoPeriod INT NOT NULL,
    secondsLeftInPeriod INT NOT NULL,
    xCoordinate INT NOT NULL,
    yCoordinate INT NOT NULL,
    [zone] INT NOT NULL,
    shotType INT NOT NULL,
    scoringPlayerTeamId INT NOT NULL,
    assistOnePlayerId INT NOT NULL,
    assistTwoPlayerId INT NOT NULL,
    scoringPlayerId INT NOT NULL,
    goalieId INT NOT NULL,
    highlightClipSharingUrl VARCHAR(255) NOT NULL,
    highlightClipId INT NOT NULL,
    discreetClipId INT NOT NULL,
    pptReplayUrl VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GameGoalEvent PRIMARY KEY(gameId, id),
    FOREIGN KEY (gameId) REFERENCES GameRaw(id),
    FOREIGN KEY (scoringPlayerTeamId) REFERENCES Team(id),
    FOREIGN KEY (scoringPlayerId) REFERENCES Player(id),
    FOREIGN KEY (assistOnePlayerId) REFERENCES Player(id),
    FOREIGN KEY (assistTwoPlayerId) REFERENCES Player(id),
    FOREIGN KEY (goalieId) REFERENCES Player(id)
);