CREATE TABLE [dbo].[CleanedGame]
(
    gameId INT NOT NULL,
    homeWinRatio FLOAT NOT NULL,
    homeRecentWinRatio FLOAT NOT NULL,
    homeRecentGoalsAvg FLOAT NOT NULL,
    homeRecentConcededGoalsAvg FLOAT NOT NULL,
    homeRecentSogAvg FLOAT NOT NULL,
    homeRecentPpgAvg FLOAT NOT NULL,
    homeRecentHitsAvg FLOAT NOT NULL,
    homeRecentPimAvg FLOAT NOT NULL,
    homeRecentBlockedShotsAvg FLOAT NOT NULL,
    homeRecentTakeawaysAvg FLOAT NOT NULL,
    homeRecentGiveawaysAvg FLOAT NOT NULL,
    homeGoalsAvg FLOAT NOT NULL,
    homeGoalsAvgAtHome FLOAT NOT NULL,
    homeRecentGoalsAvgAtHome FLOAT NOT NULL,
    homeConcededGoalsAvg FLOAT NOT NULL,
    homeConcededGoalsAvgAtHome FLOAT NOT NULL,
    homeRecentConcededGoalsAvgAtHome FLOAT NOT NULL,
    homeHoursSinceLastGame FLOAT NOT NULL,
    awayWinRatio FLOAT NOT NULL,
    awayRecentWinRatio FLOAT NOT NULL,
    awayRecentGoalsAvg FLOAT NOT NULL,
    awayRecentConcededGoalsAvg FLOAT NOT NULL,
    awayRecentSogAvg FLOAT NOT NULL,
    awayRecentPpgAvg FLOAT NOT NULL,
    awayRecentHitsAvg FLOAT NOT NULL,
    awayRecentPimAvg FLOAT NOT NULL,
    awayRecentBlockedShotsAvg FLOAT NOT NULL,
    awayRecentTakeawaysAvg FLOAT NOT NULL,
    awayRecentGiveawaysAvg FLOAT NOT NULL,
    awayGoalsAvg FLOAT NOT NULL,
    awayGoalsAvgAtAway FLOAT NOT NULL,
    awayRecentGoalsAvgAtAway FLOAT NOT NULL,
    awayConcededGoalsAvg FLOAT NOT NULL,
    awayConcededGoalsAvgAtAway FLOAT NOT NULL,
    awayRecentConcededGoalsAvgAtAway FLOAT NOT NULL,
    homeRosterOffenseValue FLOAT NOT NULL,
    homeRosterDefenseValue FLOAT NOT NULL,
    homeRosterGoalieValue FLOAT NOT NULL,
    awayRosterOffenseValue FLOAT NOT NULL,
    awayRosterDefenseValue FLOAT NOT NULL,
    awayRosterGoalieValue FLOAT NOT NULL,
    awayHoursSinceLastGame FLOAT NOT NULL,
    PRIMARY KEY(gameId),
    FOREIGN KEY (gameId) REFERENCES Game(id),
);