CREATE TABLE [dbo].[Game]
(
    id INT NOT NULL,
    homeTeamId INT NOT NULL,
    awayTeamId INT NOT NULL,
    seasonStartYear INT NOT NULL,
    gameDate DATETIME2 NOT NULL,
    homeGoals INT NOT NULL,
    awayGoals INT NOT NULL,
    homeSOG INT NOT NULL,
    awaySOG INT NOT NULL,
    homePPG INT NOT NULL,
    awayPPG INT NOT NULL,
    homePIM INT NOT NULL,
    awayPIM INT NOT NULL,
    homeFaceOffWinPercent FLOAT NOT NULL,
    awayFaceOffWinPercent FLOAT NOT NULL,
    homeBlockedShots INT NOT NULL,
    awayBlockedShots INT NOT NULL,
    homeHits INT NOT NULL,
    awayHits INT NOT NULL,
    homeTakeaways INT NOT NULL,
    awayTakeaways INT NOT NULL,
    homeGiveaways INT NOT NULL,
    awayGiveaways INT NOT NULL,
    winner INT NOT NULL,
    hasBeenPlayed BIT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (homeTeamId) REFERENCES Team(id),
    FOREIGN KEY (awayTeamId) REFERENCES Team(id),
)