CREATE TABLE [dbo].[GameRaw]
(
    Id INT NOT NULL,
    HomeTeamId INT NOT NULL,
    AwayTeamId INT NOT NULL,
    SeasonStartYear INT NOT NULL,
    GameDateUTC DATETIME2 NOT NULL,
    HomeGoals INT NOT NULL,
    AwayGoals INT NOT NULL,
    HomeSOG INT NOT NULL,
    AwaySOG INT NOT NULL,
    HomePPG INT NOT NULL,
    AwayPPG INT NOT NULL,
    HomePIM INT NOT NULL,
    AwayPIM INT NOT NULL,
    HomeFaceOffWinPercent FLOAT NOT NULL,
    AwayFaceOffWinPercent FLOAT NOT NULL,
    HomeBlockedShots INT NOT NULL,
    AwayBlockedShots INT NOT NULL,
    HomeHits INT NOT NULL,
    AwayHits INT NOT NULL,
    HomeTakeaways INT NOT NULL,
    AwayTakeaways INT NOT NULL,
    HomeGiveaways INT NOT NULL,
    AwayGiveaways INT NOT NULL,
    Winner INT NOT NULL,
    EndPeriod INT NOT NULL,
    HasBeenPlayed BIT NOT NULL,
    GameSummary VARCHAR(MAX) NULL,
    EventSummary VARCHAR(MAX) NULL,
    PlayByPlaySummary VARCHAR(MAX) NULL,
    FaceoffSummary VARCHAR(MAX) NULL,
    FaceoffComparisonSummary VARCHAR(MAX) NULL,
    RosterSummary VARCHAR(MAX) NULL,
    ShotSummary VARCHAR(MAX) NULL,
    ShiftChartSummary VARCHAR(MAX) NULL,
    ToiAwaySummary VARCHAR(MAX) NULL,
    ToiHomeSummary VARCHAR(MAX) NULL,
    ThreeMinuteRecapVideoId INT NOT NULL,
    CondensedGameVideoId INT NOT NULL,
    VenueName VARCHAR(MAX) NOT NULL,
    VenueLocation VARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_GameRaw PRIMARY KEY(Id),
    FOREIGN KEY (HomeTeamId) REFERENCES Team(Id),
    FOREIGN KEY (AwayTeamId) REFERENCES Team(Id)
);